- layer_name: conv2d_2
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0

- layer_name: conv2d_4
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0

- layer_name: conv2d_1
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0
