- layer_name: conv2d_2
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0

- layer_name: conv2d_6
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0

- layer_name: conv2d_1
  fault_type: BitFlip
  bit_flip_type: RandomBit
  probability: 1.0

- layer_name: conv2d_2
  fault_type: BitFlip
  bit_flip_type: SpecificBit
  bit_number: 31 # Max value is 31, min value is 0
  probability: 1.0

- layer_name: conv2d_5
  fault_type: BitFlip
  bit_flip_type: SpecificBit
  bit_number: 64 # Max value is 31, min value is 0
  probability: 1.0

- layer_name: flatten_1
  fault_type: BitFlip
  bit_flip_type: SpecificBit
  bit_number: 64 # Max value is 31, min value is 0
  probability: 1.0


